<%@ Page Language="VB" AutoEventWireup="false" CodeFile="EditOTHours.aspx.vb" Inherits="EditOTHours" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:Button ID="Button1" runat="server" Text="Home" />
       <asp:GridView ID="GridView1" runat="server" DataKeyNames="ID, Name, username, DateEntered" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="No records have been added." AutoGenerateEditButton="false" AutoGenerateDeleteButton="false" >
</asp:GridView>
    
    </div>
    </form>
</body>
</html>
